### ISSUE TITLE
Lenovo k5pro flash AOSP 9.0 mtp not work

### ISSUE THREAD

**Issue by kwjxqy** [phhusson/vendor_hardware_overlay#103]
Lenovo k5pro flash AOSP 9.0 mtp not work

hwservicemanager: getTransport: Cannot find entry android.hardware.usb.gadget@1.0::IUsbGadget/default in either framework or device manifest.
UsbDeviceManager: USB GADGET HAL not present in the device

UsbDeviceManagerJNI: could not open control for mtp Permission denied
UsbDeviceManagerJNI: could not open control for ptp Permission denied

How to fix?

aosp 8.1, mtp  work

**Comment by keks2293** [comment]
> 
try add 
<hal format="hidl">
        <name>android.hardware.usb.gadget</name>
        <transport>hwbinder</transport>
        <version>1.0</version>
        <interface>
            <name>IUsbGadget</name>
            <instance>default</instance>
        </interface>
    </hal>
in vendor/compabiliry_matrix.xml

**Comment by keks2293** [comment]
Same problem Z18 mini
