### ISSUE TITLE
How to debug overlays

### ISSUE THREAD

**Issue by lead4good** [phhusson/vendor_hardware_overlay#162]
Rebooting into recovery to put the overlay into the RW mounted system image is an annoying task to do. Is there a possibility to load the values in the config.xml once the phone has booted? Can I just adb push the created apk and run it or are there other things that need to be done?

**Comment by phhusson** [comment]
you can do

Adb root
Adb remount
Adb push youroverlay.apk /system/overlay
Adb shell 'stop;start'

That will soft reboot Android, but that's still more usable than going
through recovery

**Comment by lead4good** [comment]
Thanks! That does certainly speed up things :)
