### ISSUE TITLE
overlay

### ISSUE THREAD

**Issue by yura73** [phhusson/vendor_hardware_overlay#225]
Hello.
please add an overlay for Elephone Solider
[Elephone.zip](https://github.com/phhusson/vendor_hardware_overlay/files/4805449/Elephone.zip)

**Comment by Iamlooker** [comment]
you tested this?
If yes just send a pull request to this repo or do you want me to send pull request.

**Comment by yura73** [comment]
Yes, I tested it and use it myself.
if you send a transfer request, my invoices do not go through
thanks

**Comment by Iamlooker** [comment]
Bro simply click "Create Pull Request"
It will do the job itself.

**Comment by yura73** [comment]
I can't get an error

**Comment by Iamlooker** [comment]
Wait I will send pull request.

**Comment by yura73** [comment]
[frm.zip](https://github.com/phhusson/vendor_hardware_overlay/files/5390953/frm.zip)
overlay assembled by me from framework-res__auto_generated_rro.apk,framework-res.apk, my phone (Elephone Solider) and also from some common overlays GSI

**Comment by Iamlooker** [comment]
[treble-overlay-elephone-solider.zip](https://github.com/phhusson/vendor_hardware_overlay/files/5391615/treble-overlay-elephone-solider.zip)


try this overlay and report back on telegram on @Lo_oKeR
