### ISSUE TITLE
Samsung galaxy S10e(snapdragon) overlay

### ISSUE THREAD

**Issue by Laikar** [phhusson/vendor_hardware_overlay#239]
There seems to be an overlay for the s10e, but i think it is made for the exynoss models and is beeing aplied to both snapdragon and exynoss models..
On the snapdragon models, the proximity sensor isn't working.
I have managed to decompile the framework-res apk, and make the tests, but i don't know if i should make a new overlay for the snapdragon variant or update the existing one.

**Comment by phhusson** [comment]
Did you tick "enable extra sensors" in treble settings?

**Comment by Laikar** [comment]
Yes, under samsung settings all ticks are enabled but reversed wireless charging, all on qualcomm features, none on doze and on misc only expose aux cameras and force-disable a2poffload

**Comment by phhusson** [comment]
Ok give the result of adb shell dumpsys sensorservice

**Comment by Laikar** [comment]
Here you go
[sensors.txt](https://github.com/phhusson/vendor_hardware_overlay/files/5010232/sensors.txt)

**Comment by phhusson** [comment]
`com.samsung.sensor.physical_proximity(65592)` the proximity sensor is here

I'll need to confirm the name of that sensor is supported in my GSI, I'm not totally sure what was the name on my device

**Comment by Laikar** [comment]
It doesn't appear on the [sensor testing app](https://play.google.com/store/apps/details?id=ru.andr7e.sensortest) i'm using

**Comment by phhusson** [comment]
Yeah it's normal that it's not appearing in a testing app, it shouldn't prevent screen off during calls.

On my exynos S10e, I have com.samsung.sensor.physical_proximity, that's identical right?

Just to be sure, how do you test whether proximity sensor works?

**Comment by Laikar** [comment]
I just realized the proximity sensor is actually working, sorry for bothering with it.
I thought it wasn't working because the phone randomly turns on while on my pocket and the app didn't recognise it.
[Pictures of the app](https://imgur.com/a/ro3hFru)
But the phone screen actually turns off while on a call/ listening to audio and whatsapp/telegram audios (the bottom speaker doesn't turn off, but i don't remember if it did on stock and don't really use this feature this way)

**Comment by phhusson** [comment]
Well yeah proximity on Samsung is pretty weird.
Basically Android declares a generic proximity sensor type, but Samsung has
actually different types of proximity sensor depending on the use case, so
they choose to declare two proximity sensors, none which responds to
Android generic proximity sensor.

They have one proximity sensor which is a fairly standard LED+sensor near
the 4G of the status bar, but it detects proximity at only one place, so
considering the size of phone nowadays, it could be wrong, and there is
another proximity sensor which is the touchscreen, so the whole screen can
act as a proximity sensor.

I'm not totally sure how Samsung handles it, I'm guessing it's something
along the lines of "if hardware proximity sensor says near, transition to
near, and transition to far only if both hardware proximity sensor and
touchscreen agree on far"
