### ISSUE TITLE
Night Light not working - Huawei Y9 2019(JKM-LX1)

### ISSUE THREAD

**Issue by SilverCrow33** [phhusson/vendor_hardware_overlay#418]
I created an overlay for Huawei Y9 2019 Model JKM, auto-Brightness is working but i have lost Night Light feature. The option is showing as Ambient Display(LiveDisplay) and none of the available options(auto, on, off) in Ambient Display(LiveDisplay)  that i select works. I just want to fix this bug as everything else is working fine.

I extracted the framework-res.apk from my stock android 9.0 rom.

**Comment by SilverCrow33** [comment]
Issue Solved.

**Comment by phhusson** [comment]
how?

Le sam. 8 janv. 2022 à 07:43, SilverCrow33 ***@***.***> a
écrit :

**Comment by SilverCrow33** [comment]
In my stock framework-res.apk "config_setColorTransformAccelerated" was set on false:

`<item type="bool" name="config_nightDisplayAvailable">@bool/config_setColorTransformAccelerated</item>`
`<bool name="config_setColorTransformAccelerated">false</bool>`

when I looked into your NightMode overlay I saw that it should be true and just changed this part and night light was working.
