### ISSUE TITLE
Tethering overlay might require some looking into

### ISSUE THREAD

**Issue by Kethen** [phhusson/vendor_hardware_overlay#549]
https://github.com/phhusson/vendor_hardware_overlay/tree/pie/Tethering

Being an override in /system/product with priority 10 it overrides the tethering overlay in vendor, and it breaks wifihotspot on galaxy s7; it might be common for exynos devices to have to the following overlay instead
```
    <string-array translatable="false" name="config_tether_wifi_regexs">
        <item>"wlan\\d"</item>
        <item>"swlan0"</item>
    </string-array>
```

and for older kernels

```
    <bool translatable="false" name="config_tether_enable_bpf_offload">false</bool>
```

A workaround is to remove the overlay when such conflict occurs. Perhaps the overlay can be less shotgun and hinges on some mtk props to activate? Or perhaps the workaround of removing `/system/product/overlay/treble-overlay-tethering.apk` can be documented in Common Issues and fixes on the wiki

**Comment by phhusson** [comment]
For config_tether_wifi_regexs, you can just add swlan0 to the list
For bpf it'll need to make a new overlay, enabled by property, which we can enable for kernels <=4.4
