### ISSUE TITLE
[Question] build for testing

### ISSUE THREAD

**Issue by AlexandreMarkus** [phhusson/vendor_hardware_overlay#561]
Hi @phhusson ,

I would like to do some tests on my device by adding some attribute. Is there a way to build the overlay locally and install it on my device running [system-squeak-arm64-ab-vndklite-gapps-secure.img.xz](https://github.com/phhusson/treble_experimentations/releases/download/v414/system-squeak-arm64-ab-vndklite-gapps-secure.img.xz)? 
Thank you!

**Comment by ghost** [comment]
https://github.com/phhusson/treble_experimentations/wiki/How-to-create-an-overlay%3F
