### ISSUE TITLE
Bluetooth / calling Bluetooth can't hear 

### ISSUE THREAD

**Issue by AgressiveKraytos** [phhusson/vendor_hardware_overlay#62]
Hello I'm new to this so please bare with me just wanted to know if any one is working on this fix for Bluetooth and calling Bluetooth can't hear we may had a fix but its not sticking after reboot. I know phusson has sent out and made a report about it . but was just asking if anything is being done  I know you guys are busy with a lot but hopefully I can get an answer thank you for your time oh device Moto E5 plus Hannah again Thank you for your hard work ...

**Comment by penn5** [comment]
Please open an issue at https://github.com/phhusson/treble_experimentations.
