### ISSUE TITLE
MiA2Lite display cutout not supported on treble aosp android-8.1?

### ISSUE THREAD

**Issue by wico** [phhusson/vendor_hardware_overlay#70]
Hi,

in the hope not asking a too stupid question:

I successfully run android-8.1.0_r61 (plain AOSP / treble_arm64_bvN) compiled by using https://github.com/phhusson/treble_manifest (branch android-8.1) with no additional patches applied on a Xiaomi Mi A2 Lite.

So far, so good, everything works as expected, except the display cutout: The statusbar-items are hidden behind the notch, the typical issue with notch-devices and custom ROMs.

So I checked a bit more and can see this:

```
phhgsi_arm64_ab:/system # cat /data/resource-cache/overlays.list                                                                                                                                                  
/system/overlay/treble-overlay-NightMode.apk /data/resource-cache/system@overlay@treble-overlay-NightMode.apk@idmap
/system/overlay/treble-overlay-devinputjack.apk /data/resource-cache/system@overlay@treble-overlay-devinputjack.apk@idmap
/system/overlay/treble-overlay-xiaomi-mia2lite.apk /data/resource-cache/system@overlay@treble-overlay-xiaomi-mia2lite.apk@idmap
/system/overlay/treble-overlay-webview.apk /data/resource-cache/system@overlay@treble-overlay-webview.apk@idmap
```

Also, in /system/overlay/ there is the "treble-overlay-xiaomi-mia2lite.apk".

So, to me it looks like the mia2lite overlay is there and it is loaded.

If I understand: https://github.com/phhusson/vendor_hardware_overlay/blob/master/Xiaomi/MiA2Lite/res/values/notch.xml#L26 correctly, when this above mentioned overlay is loaded, the notch should be supported in android 8, or?

I ask, because the statusbar still gets hidden behind the notch as mentioned. The only way to work around that is to do a (as root inside a adb-shell):

`wm overscan 0,80,0,0`

If I build the exact same thing but with android-9, the notch is supported and the statusbar perfectly fits it.

Thank you for an answer!

Martin

**Comment by AndroPlus-org** [comment]
Android 8.x doesn't support notch. config_mainBuiltInDisplayCutout is used for 9.0+, but it's included on master as master is the main branch for this project.

**Comment by wico** [comment]
Understand. Too bad.
I wonder how e.g. Xiaomi "fixed" that when they started to ship the Mi A2 Lite (daisy) with a notch and Android 8.1 (oreo).

**Comment by kaijaa** [comment]
#70

**Comment by phhusson** [comment]
well 8.1 is long dead.
