### ISSUE TITLE
Snapdragon 425 fix not working on Zenfone Live L1 (X00RD)

### ISSUE THREAD

**Issue by v555574** [phhusson/vendor_hardware_overlay#74]
There are glitches and artifacts everywhere. After manually adding "debug.hwui.renderer=opengl" in build.prop everything is fine.

**Comment by phhusson** [comment]
What's your getprop ro.product.board ?

**Comment by v555574** [comment]
MSM8917

**Comment by phhusson** [comment]
Ok so we need to change
https://github.com/phhusson/device_phh_treble/blob/android-9.0/rw-system.sh
line (getprop ro.product.board | grep -qE -e msm8917 -e msm8937 -e msm8940
And edit to have qiE instead to match uppercased msm
